# Generated by Django 5.2.15 on 2026-07-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='branch_id',
        ),
    ]
