from django.urls import path
from contexts.employees import views

app_name = "employees"

urlpatterns = [
    path("dashboard/", views.HRMSDashboardView.as_view(), name="dashboard"),
    path("<uuid:tenant_id>/dashboard/", views.HRMSDashboardView.as_view(), name="dashboard_tenant"),
    
    path("directory/", views.EmployeeListView.as_view(), name="employee_list"),
    path("<uuid:tenant_id>/directory/", views.EmployeeListView.as_view(), name="employee_list_tenant"),
    path("directory/create/", views.EmployeeCreateView.as_view(), name="employee_create"),
    path("<uuid:tenant_id>/directory/create/", views.EmployeeCreateView.as_view(), name="employee_create_tenant"),
    path("directory/<uuid:pk>/edit/", views.EmployeeUpdateView.as_view(), name="employee_update"),
    path("<uuid:tenant_id>/directory/<uuid:pk>/edit/", views.EmployeeUpdateView.as_view(), name="employee_update_tenant"),
    path("directory/<uuid:pk>/delete/", views.EmployeeDeleteView.as_view(), name="employee_delete"),
    path("<uuid:tenant_id>/directory/<uuid:pk>/delete/", views.EmployeeDeleteView.as_view(), name="employee_delete_tenant"),
    path("directory/<uuid:pk>/status/", views.EmployeeToggleStatusView.as_view(), name="employee_toggle_status"),
    path("<uuid:tenant_id>/directory/<uuid:pk>/status/", views.EmployeeToggleStatusView.as_view(), name="employee_toggle_status_tenant"),
    path("directory/<uuid:pk>/lock/", views.EmployeeToggleLockView.as_view(), name="employee_toggle_lock"),
    path("<uuid:tenant_id>/directory/<uuid:pk>/lock/", views.EmployeeToggleLockView.as_view(), name="employee_toggle_lock_tenant"),
    path("directory/<uuid:pk>/reset-password/", views.EmployeeResetPasswordView.as_view(), name="employee_reset_password"),
    path("<uuid:tenant_id>/directory/<uuid:pk>/reset-password/", views.EmployeeResetPasswordView.as_view(), name="employee_reset_password_tenant"),
    
    path("roles/", views.RoleListView.as_view(), name="role_list"),
    path("<uuid:tenant_id>/roles/", views.RoleListView.as_view(), name="role_list_tenant"),
    path("roles/create/", views.RoleCreateView.as_view(), name="role_create"),
    path("<uuid:tenant_id>/roles/create/", views.RoleCreateView.as_view(), name="role_create_tenant"),
    path("roles/<uuid:pk>/edit/", views.RoleUpdateView.as_view(), name="role_update"),
    path("<uuid:tenant_id>/roles/<uuid:pk>/edit/", views.RoleUpdateView.as_view(), name="role_update_tenant"),
    path("roles/<uuid:pk>/delete/", views.RoleDeleteView.as_view(), name="role_delete"),
    path("<uuid:tenant_id>/roles/<uuid:pk>/delete/", views.RoleDeleteView.as_view(), name="role_delete_tenant"),
    path("roles/matrix/", views.RolePermissionMatrixView.as_view(), name="role_matrix"),
    path("<uuid:tenant_id>/roles/matrix/", views.RolePermissionMatrixView.as_view(), name="role_matrix_tenant"),
    
    path("departments/", views.DepartmentListView.as_view(), name="department_list"),
    path("<uuid:tenant_id>/departments/", views.DepartmentListView.as_view(), name="department_list_tenant"),
    path("departments/create/", views.DepartmentCreateView.as_view(), name="department_create"),
    path("<uuid:tenant_id>/departments/create/", views.DepartmentCreateView.as_view(), name="department_create_tenant"),
    path("departments/create/quick/", views.DepartmentQuickCreateView.as_view(), name="department_create_quick"),
    path("departments/<uuid:pk>/edit/", views.DepartmentUpdateView.as_view(), name="department_update"),
    path("<uuid:tenant_id>/departments/<uuid:pk>/edit/", views.DepartmentUpdateView.as_view(), name="department_update_tenant"),
    path("departments/<uuid:pk>/delete/", views.DepartmentDeleteView.as_view(), name="department_delete"),
    path("<uuid:tenant_id>/departments/<uuid:pk>/delete/", views.DepartmentDeleteView.as_view(), name="department_delete_tenant"),

    path("designations/", views.DesignationListView.as_view(), name="designation_list"),
    path("<uuid:tenant_id>/designations/", views.DesignationListView.as_view(), name="designation_list_tenant"),
    path("designations/create/", views.DesignationCreateView.as_view(), name="designation_create"),
    path("<uuid:tenant_id>/designations/create/", views.DesignationCreateView.as_view(), name="designation_create_tenant"),
    path("designations/create/quick/", views.DesignationQuickCreateView.as_view(), name="designation_create_quick"),
    path("designations/<uuid:pk>/edit/", views.DesignationUpdateView.as_view(), name="designation_update"),
    path("<uuid:tenant_id>/designations/<uuid:pk>/edit/", views.DesignationUpdateView.as_view(), name="designation_update_tenant"),
    path("designations/<uuid:pk>/delete/", views.DesignationDeleteView.as_view(), name="designation_delete"),
    path("<uuid:tenant_id>/designations/<uuid:pk>/delete/", views.DesignationDeleteView.as_view(), name="designation_delete_tenant"),

    path("shifts/", views.ShiftListView.as_view(), name="shift_list"),
    path("<uuid:tenant_id>/shifts/", views.ShiftListView.as_view(), name="shift_list_tenant"),
    path("shifts/create/", views.ShiftCreateView.as_view(), name="shift_create"),
    path("<uuid:tenant_id>/shifts/create/", views.ShiftCreateView.as_view(), name="shift_create_tenant"),
    path("shifts/<uuid:pk>/edit/", views.ShiftUpdateView.as_view(), name="shift_update"),
    path("<uuid:tenant_id>/shifts/<uuid:pk>/edit/", views.ShiftUpdateView.as_view(), name="shift_update_tenant"),
    path("shifts/<uuid:pk>/delete/", views.ShiftDeleteView.as_view(), name="shift_delete"),
    path("<uuid:tenant_id>/shifts/<uuid:pk>/delete/", views.ShiftDeleteView.as_view(), name="shift_delete_tenant"),

    path("weeklyoffs/", views.WeeklyOffListView.as_view(), name="weeklyoff_list"),
    path("<uuid:tenant_id>/weeklyoffs/", views.WeeklyOffListView.as_view(), name="weeklyoff_list_tenant"),
    path("weeklyoffs/create/", views.WeeklyOffCreateView.as_view(), name="weeklyoff_create"),
    path("<uuid:tenant_id>/weeklyoffs/create/", views.WeeklyOffCreateView.as_view(), name="weeklyoff_create_tenant"),
    path("weeklyoffs/<uuid:pk>/edit/", views.WeeklyOffUpdateView.as_view(), name="weeklyoff_update"),
    path("<uuid:tenant_id>/weeklyoffs/<uuid:pk>/edit/", views.WeeklyOffUpdateView.as_view(), name="weeklyoff_update_tenant"),
    path("weeklyoffs/<uuid:pk>/delete/", views.WeeklyOffDeleteView.as_view(), name="weeklyoff_delete"),
    path("<uuid:tenant_id>/weeklyoffs/<uuid:pk>/delete/", views.WeeklyOffDeleteView.as_view(), name="weeklyoff_delete_tenant"),

    path("attendance/", views.AttendanceListView.as_view(), name="attendance_list"),
    path("<uuid:tenant_id>/attendance/", views.AttendanceListView.as_view(), name="attendance_list_tenant"),
    path("attendance/create/", views.AttendanceCreateView.as_view(), name="attendance_create"),
    path("<uuid:tenant_id>/attendance/create/", views.AttendanceCreateView.as_view(), name="attendance_create_tenant"),
    path("attendance/<uuid:pk>/edit/", views.AttendanceUpdateView.as_view(), name="attendance_update"),
    path("<uuid:tenant_id>/attendance/<uuid:pk>/edit/", views.AttendanceUpdateView.as_view(), name="attendance_update_tenant"),
    path("attendance/<uuid:pk>/delete/", views.AttendanceDeleteView.as_view(), name="attendance_delete"),
    path("<uuid:tenant_id>/attendance/<uuid:pk>/delete/", views.AttendanceDeleteView.as_view(), name="attendance_delete_tenant"),

    path("leaves/", views.LeaveRequestListView.as_view(), name="leave_list"),
    path("<uuid:tenant_id>/leaves/", views.LeaveRequestListView.as_view(), name="leave_list_tenant"),
    path("leaves/create/", views.LeaveRequestCreateView.as_view(), name="leave_create"),
    path("<uuid:tenant_id>/leaves/create/", views.LeaveRequestCreateView.as_view(), name="leave_create_tenant"),
    path("leaves/<uuid:pk>/edit/", views.LeaveRequestUpdateView.as_view(), name="leave_update"),
    path("<uuid:tenant_id>/leaves/<uuid:pk>/edit/", views.LeaveRequestUpdateView.as_view(), name="leave_update_tenant"),
    path("leaves/<uuid:pk>/delete/", views.LeaveRequestDeleteView.as_view(), name="leave_delete"),
    path("<uuid:tenant_id>/leaves/<uuid:pk>/delete/", views.LeaveRequestDeleteView.as_view(), name="leave_delete_tenant"),

    path("payroll/", views.SalaryPayoutListView.as_view(), name="payroll_list"),
    path("<uuid:tenant_id>/payroll/", views.SalaryPayoutListView.as_view(), name="payroll_list_tenant"),
    path("payroll/create/", views.SalaryPayoutCreateView.as_view(), name="payroll_create"),
    path("<uuid:tenant_id>/payroll/create/", views.SalaryPayoutCreateView.as_view(), name="payroll_create_tenant"),
    path("payroll/<uuid:pk>/edit/", views.SalaryPayoutUpdateView.as_view(), name="payroll_update"),
    path("<uuid:tenant_id>/payroll/<uuid:pk>/edit/", views.SalaryPayoutUpdateView.as_view(), name="payroll_update_tenant"),
    path("payroll/<uuid:pk>/delete/", views.SalaryPayoutDeleteView.as_view(), name="payroll_delete"),
    path("<uuid:tenant_id>/payroll/<uuid:pk>/delete/", views.SalaryPayoutDeleteView.as_view(), name="payroll_delete_tenant"),

    path("documents/", views.EmployeeDocumentListView.as_view(), name="document_list"),
    path("<uuid:tenant_id>/documents/", views.EmployeeDocumentListView.as_view(), name="document_list_tenant"),
    path("documents/create/", views.EmployeeDocumentCreateView.as_view(), name="document_create"),
    path("<uuid:tenant_id>/documents/create/", views.EmployeeDocumentCreateView.as_view(), name="document_create_tenant"),
    path("documents/<uuid:pk>/edit/", views.EmployeeDocumentUpdateView.as_view(), name="document_update"),
    path("<uuid:tenant_id>/documents/<uuid:pk>/edit/", views.EmployeeDocumentUpdateView.as_view(), name="document_update_tenant"),
    path("documents/<uuid:pk>/delete/", views.EmployeeDocumentDeleteView.as_view(), name="document_delete"),
    path("<uuid:tenant_id>/documents/<uuid:pk>/delete/", views.EmployeeDocumentDeleteView.as_view(), name="document_delete_tenant"),

    path("reports/", views.HRReportsView.as_view(), name="reports"),
    path("<uuid:tenant_id>/reports/", views.HRReportsView.as_view(), name="reports_tenant"),
]
