# Generated by Django 5.2.15 on 2026-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiter_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
