# Generated by Django 5.2.15 on 2026-07-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_order_waiter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='offline_reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
