# Generated by Django 5.2.15 on 2026-07-08 09:13

import django.db.models.deletion
import shared.infrastructure.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_kotitem_is_completed_order_offline_reference_id'),
        ('tenants', '0003_remove_floor_branch_remove_floor_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('job_type', models.CharField(choices=[('customer_receipt', 'Customer Copy'), ('restaurant_receipt', 'Restaurant Copy'), ('kot_ticket', 'Kitchen Order Ticket')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('content_text', models.TextField(help_text='Formatted ASCII text for thermal roll display.')),
                ('content_escpos', models.BinaryField(help_text='Raw ESC/POS byte stream for printer hardware.')),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='ordering.invoice')),
                ('kot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='ordering.kot')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='ordering.order')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'print_job',
                'ordering': ['created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('kot__isnull', True)), fields=('tenant', 'order', 'job_type'), name='uq_print_job__receipt_once'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('kot__isnull', False)), fields=('tenant', 'order', 'kot', 'job_type'), name='uq_print_job__kot_once')],
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
    ]
