# Generated by Django 5.2.15 on 2026-07-08 18:23

import django.db.models.deletion
import shared.infrastructure.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_alter_printjob_status_refund'),
        ('tenants', '0003_remove_floor_branch_remove_floor_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCombo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('combo_offer_id', models.UUIDField(blank=True, null=True)),
                ('name_snapshot', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='ordering.order')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'order_combo',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ordering.ordercombo'),
        ),
    ]
