# Generated by Django 5.2.15 on 2026-07-09 19:37

from django.db import migrations, models


def deduplicate_daily_counters(apps, schema_editor):
    DailyCounter = apps.get_model("ordering", "DailyCounter")
    duplicates = (
        DailyCounter.objects.values("tenant_id", "scope", "series", "date")
        .annotate(count=models.Count("id"), max_last_number=models.Max("last_number"))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        rows = list(
            DailyCounter.objects.filter(
                tenant_id=duplicate["tenant_id"],
                scope=duplicate["scope"],
                series=duplicate["series"],
                date=duplicate["date"],
            ).order_by("-last_number", "pk")
        )
        if not rows:
            continue

        keeper = rows[0]
        for row in rows[1:]:
            if row.pk != keeper.pk:
                row.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_ordercombo_orderitem_combo'),
        ('tenants', '0004_remove_branch_tenant_remove_cashcounter_branch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailycounter',
            name='uq_daily_counter__key',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='ix_order__open',
        ),
        migrations.RemoveField(
            model_name='dailycounter',
            name='location_id',
        ),
        migrations.RunPython(
            deduplicate_daily_counters,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='kot',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location_id',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_deleted', False), ('status', 'open')), fields=['tenant', 'status'], name='ix_order__open'),
        ),
        migrations.AddConstraint(
            model_name='dailycounter',
            constraint=models.UniqueConstraint(fields=('tenant', 'scope', 'series', 'date'), name='uq_daily_counter__key'),
        ),
    ]
