# Generated by Django 5.2.15 on 2026-07-14 07:31

import django.db.models.deletion
import shared.infrastructure.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_remove_dailycounter_uq_daily_counter__key_and_more'),
        ('tenants', '0004_remove_branch_tenant_remove_cashcounter_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSPrinterConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('terminal_id', models.UUIDField(blank=True, help_text='POS terminal device UUID. None = global/location-level config.', null=True)),
                ('location_id', models.UUIDField(blank=True, help_text='Store/outlet UUID. Used when terminal_id is not set.', null=True)),
                ('printer_name', models.CharField(blank=True, help_text='Stable printer identity from Print Service (e.g. Windows printer queue name).', max_length=255)),
                ('printer_display_name', models.CharField(blank=True, help_text='Human-readable printer name for display in the UI.', max_length=255)),
                ('connection_type', models.CharField(blank=True, help_text='Cached connection type (USB, Network, Bluetooth, Local).', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_print', models.BooleanField(default=True, help_text='Automatically print receipt after successful transaction.')),
                ('paper_width', models.CharField(choices=[('80mm', '80mm'), ('58mm', '58mm')], default='80mm', max_length=10)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'POS Printer Configuration',
                'verbose_name_plural': 'POS Printer Configurations',
                'db_table': 'pos_printer_config',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('terminal_id__isnull', False)), fields=('tenant', 'terminal_id'), name='uq_pos_printer_config__terminal')],
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
    ]
