from django.urls import path
from contexts.catalog import views

app_name = "catalog"

urlpatterns = [
    path("categories/", views.CategoryListView.as_view(), name="category_list"),
    path("<uuid:tenant_id>/categories/", views.CategoryListView.as_view(), name="category_list_tenant"),
    path("categories/create-ajax/", views.CategoryCreateAjaxView.as_view(), name="category_create_ajax"),
    path("<uuid:tenant_id>/categories/create-ajax/", views.CategoryCreateAjaxView.as_view(), name="category_create_ajax_tenant"),
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("<uuid:tenant_id>/products/", views.ProductListView.as_view(), name="product_list_tenant"),
    path("products/create/", views.ProductCreateView.as_view(), name="product_create"),
    path("<uuid:tenant_id>/products/create/", views.ProductCreateView.as_view(), name="product_create_tenant"),
    path("products/<uuid:pk>/edit/", views.ProductUpdateView.as_view(), name="product_update"),
    path("<uuid:tenant_id>/products/<uuid:pk>/edit/", views.ProductUpdateView.as_view(), name="product_update_tenant"),
    path("products/<uuid:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("<uuid:tenant_id>/products/<uuid:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete_tenant"),
    path("modifiers/", views.ModifierGroupListView.as_view(), name="modifier_group_list"),
    path("<uuid:tenant_id>/modifiers/", views.ModifierGroupListView.as_view(), name="modifier_group_list_tenant"),
    path("modifiers/create/", views.ModifierGroupCreateView.as_view(), name="modifier_group_create"),
    path("<uuid:tenant_id>/modifiers/create/", views.ModifierGroupCreateView.as_view(), name="modifier_group_create_tenant"),
    path("modifiers/<uuid:pk>/edit/", views.ModifierGroupUpdateView.as_view(), name="modifier_group_update"),
    path("<uuid:tenant_id>/modifiers/<uuid:pk>/edit/", views.ModifierGroupUpdateView.as_view(), name="modifier_group_update_tenant"),
    path("modifiers/<uuid:pk>/delete/", views.ModifierGroupDeleteView.as_view(), name="modifier_group_delete"),
    path("<uuid:tenant_id>/modifiers/<uuid:pk>/delete/", views.ModifierGroupDeleteView.as_view(), name="modifier_group_delete_tenant"),
    path("modifiers/<uuid:group_pk>/options/", views.ModifierOptionManageView.as_view(), name="modifier_option_manage"),
    path("<uuid:tenant_id>/modifiers/<uuid:group_pk>/options/", views.ModifierOptionManageView.as_view(), name="modifier_option_manage_tenant"),
    path("modifiers/<uuid:group_pk>/options/create/", views.ModifierCreateView.as_view(), name="modifier_option_create"),
    path("<uuid:tenant_id>/modifiers/<uuid:group_pk>/options/create/", views.ModifierCreateView.as_view(), name="modifier_option_create_tenant"),
    path("modifiers/options/<uuid:pk>/edit/", views.ModifierUpdateView.as_view(), name="modifier_option_update"),
    path("<uuid:tenant_id>/modifiers/options/<uuid:pk>/edit/", views.ModifierUpdateView.as_view(), name="modifier_option_update_tenant"),
    path("modifiers/options/<uuid:pk>/delete/", views.ModifierDeleteView.as_view(), name="modifier_option_delete"),
    path("<uuid:tenant_id>/modifiers/options/<uuid:pk>/delete/", views.ModifierDeleteView.as_view(), name="modifier_option_delete_tenant"),
    path("modifiers/options/<uuid:pk>/clone/", views.ModifierCloneView.as_view(), name="modifier_option_clone"),
    path("<uuid:tenant_id>/modifiers/options/<uuid:pk>/clone/", views.ModifierCloneView.as_view(), name="modifier_option_clone_tenant"),
    path("modifiers/options/<uuid:pk>/toggle-status/", views.ModifierToggleStatusView.as_view(), name="modifier_option_toggle_status"),
    path("<uuid:tenant_id>/modifiers/options/<uuid:pk>/toggle-status/", views.ModifierToggleStatusView.as_view(), name="modifier_option_toggle_status_tenant"),
    path("modifiers/analytics/", views.ModifierAnalyticsView.as_view(), name="modifier_analytics"),
    path("<uuid:tenant_id>/modifiers/analytics/", views.ModifierAnalyticsView.as_view(), name="modifier_analytics_tenant"),
    path("combos/", views.ComboOfferListView.as_view(), name="combo_list"),
    path("<uuid:tenant_id>/combos/", views.ComboOfferListView.as_view(), name="combo_list_tenant"),
    path("combos/create/", views.ComboOfferCreateView.as_view(), name="combo_create"),
    path("<uuid:tenant_id>/combos/create/", views.ComboOfferCreateView.as_view(), name="combo_create_tenant"),
    path("combos/<uuid:pk>/edit/", views.ComboOfferUpdateView.as_view(), name="combo_update"),
    path("<uuid:tenant_id>/combos/<uuid:pk>/edit/", views.ComboOfferUpdateView.as_view(), name="combo_update_tenant"),
]
