"""Order Combo grouping entities."""
from django.db import models

from shared.tenancy.models import TenantAwareModel


class OrderCombo(TenantAwareModel):
    """Groups a set of OrderItems that satisfy a ComboOffer."""
    order = models.ForeignKey("ordering.Order", on_delete=models.CASCADE, related_name="combos")
    
    # Reference to the catalog combo that spawned this
    combo_offer_id = models.UUIDField(null=True, blank=True)
    
    # Snapshot fields so we don't lose data if catalog changes
    name_snapshot = models.CharField(max_length=160)
    
    # The fixed price of the combo itself, before tax, or the value of the deal
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    
    # Total savings generated by this combo (Sum of original base prices - price)
    savings = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    class Meta(TenantAwareModel.Meta):
        db_table = "order_combo"
        
    def __str__(self) -> str:
        return self.name_snapshot
