# Generated by Django 5.2.15 on 2026-06-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('dirty', 'Cleaning'), ('billing', 'Billing Pending'), ('blocked', 'Blocked'), ('merged', 'Merged')], default='vacant', max_length=15),
        ),
    ]
