# Generated by Django 5.2.15 on 2026-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_diningtable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diningtable',
            name='assigned_waiter_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
