# Generated by Django 5.2.15 on 2026-06-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_diningtable_assigned_waiter_id'),
        ('tenants', '0002_tenant_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='floor',
            name='uq_r_floor__branch_name',
        ),
        migrations.RemoveIndex(
            model_name='floor',
            name='ix_r_floor__branch_order',
        ),
        migrations.RemoveConstraint(
            model_name='tablesection',
            name='uq_r_section__floor_name',
        ),
        migrations.RemoveConstraint(
            model_name='diningtable',
            name='uq_r_table__floor_number',
        ),
        migrations.RemoveIndex(
            model_name='diningtable',
            name='ix_r_table__floor_status',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='diningtable',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='tablesection',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='tablesection',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='diningtable',
            name='section',
        ),
        migrations.AddField(
            model_name='diningtable',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.branch'),
        ),
        migrations.AddConstraint(
            model_name='diningtable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'number'), name='uq_r_table__branch_number'),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='TableSection',
        ),
    ]
