# Generated by Django 5.2.15 on 2026-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_floor_branch_remove_floor_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
