# Generated by Django 5.2.15 on 2026-07-09 19:37

import django.db.models.deletion
import shared.infrastructure.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_branch_is_archived_branch_is_default_branch_logo_and_more'),
        ('tenants', '0004_remove_branch_tenant_remove_cashcounter_branch_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RestaurantGSTProfile',
                    fields=[
                        ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                        ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                        ('is_deleted', models.BooleanField(db_index=True, default=False)),
                        ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                        ('gstin', models.CharField(help_text='15-character GSTIN', max_length=15)),
                        ('legal_name', models.CharField(help_text='Legal name on GST certificate', max_length=255)),
                        ('state_code', models.CharField(help_text='2-digit state code from GSTIN', max_length=2)),
                        ('registration_type', models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('unregistered', 'Unregistered')], default='regular', max_length=20)),
                        ('pan', models.CharField(blank=True, help_text='PAN extracted from GSTIN', max_length=10)),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'restaurant_gst_profile',
                        'ordering': ['-created_at'],
                        'get_latest_by': 'created_at',
                        'abstract': False,
                    },
                    bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='RestaurantSettings',
                    fields=[
                        ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                        ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                        ('is_deleted', models.BooleanField(db_index=True, default=False)),
                        ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                        ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                        ('invoice_footer', models.TextField(blank=True)),
                        ('auto_accept_orders', models.BooleanField(default=False, help_text='Automatically accept incoming orders')),
                        ('default_order_type', models.CharField(default='dine_in', help_text='Default order type when not specified', max_length=20)),
                        ('enable_customer_self_ordering', models.BooleanField(default=False, help_text='Allow QR-based self-ordering')),
                        ('table_layout_mode', models.CharField(default='grid', help_text='Floor plan display mode: grid, freeform', max_length=20)),
                        ('notification_settings', models.JSONField(blank=True, default=dict)),
                        ('theme', models.JSONField(blank=True, default=dict)),
                    ],
                    options={
                        'db_table': 'restaurant_settings',
                        'ordering': ['-created_at'],
                        'get_latest_by': 'created_at',
                        'abstract': False,
                    },
                    bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
                ),
            ],
        ),
        # Drop all constraints/indexes referencing 'branch' fields BEFORE removing those fields.
        # SQLite _remake_table recreates the full table with all constraints, so any constraint
        # referencing a field being removed must be dropped first.

        # --- Branch: drop restaurant-referencing constraints before removing the field ---
        migrations.RemoveIndex(
            model_name='branch',
            name='ix_r_branch__rest_status',
        ),
        migrations.RemoveConstraint(
            model_name='branch',
            name='uq_r_branch__restaurant_code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='tenant',
        ),

        # --- CashCounter: drop branch-referencing constraint before removing branch field ---
        migrations.RemoveConstraint(
            model_name='cashcounter',
            name='uq_r_counter__branch_name',
        ),
        migrations.RemoveField(
            model_name='cashcounter',
            name='branch',
        ),

        # --- BusinessHours: drop branch-referencing constraint before removing branch field ---
        migrations.RemoveConstraint(
            model_name='businesshours',
            name='uq_r_hours__branch_day',
        ),
        migrations.RemoveField(
            model_name='businesshours',
            name='branch',
        ),

        # --- KitchenStation: drop branch-referencing index+constraint before removing branch field ---
        migrations.RemoveIndex(
            model_name='kitchenstation',
            name='ix_r_station__branch_active',
        ),
        migrations.RemoveConstraint(
            model_name='kitchenstation',
            name='uq_r_station__branch_code',
        ),
        migrations.RemoveField(
            model_name='kitchenstation',
            name='branch',
        ),

        # --- Holiday: drop branch-referencing constraint before removing branch field ---
        migrations.RemoveConstraint(
            model_name='holiday',
            name='uq_r_holiday__branch_date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='branch',
        ),

        # --- DiningTable: drop branch-referencing constraint before removing branch field ---
        migrations.RemoveConstraint(
            model_name='diningtable',
            name='uq_r_table__branch_number',
        ),
        migrations.RemoveField(
            model_name='diningtable',
            name='branch',
        ),

        # --- BranchSettings: has inline constraint uq_r_settings__branch on ('branch',) ---
        migrations.RemoveConstraint(
            model_name='branchsettings',
            name='uq_r_settings__branch',
        ),
        migrations.RemoveField(
            model_name='branchsettings',
            name='branch',
        ),

        # --- Printer: drop branch-referencing index+constraint before removing branch field ---
        migrations.RemoveIndex(
            model_name='printer',
            name='ix_r_printer__branch_kind',
        ),
        migrations.RemoveConstraint(
            model_name='printer',
            name='uq_r_printer__branch_code',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='branch',
        ),

        # --- BranchGSTProfile: has inline constraint uq_r_gst__branch on ('branch',) ---
        migrations.RemoveConstraint(
            model_name='branchgstprofile',
            name='uq_r_gst__branch',
        ),
        migrations.RemoveField(
            model_name='branchgstprofile',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='branchgstprofile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='branchsettings',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='If true, closed on this day (open/close times ignored)'),
        ),
        migrations.AddIndex(
            model_name='kitchenstation',
            index=models.Index(fields=['tenant', 'is_active'], name='ix_r_station__tenant_active'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['tenant', 'kind'], name='ix_r_printer__tenant_kind'),
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'day_of_week'), name='uq_r_hours__tenant_day'),
        ),
        migrations.AddConstraint(
            model_name='cashcounter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'name'), name='uq_r_counter__tenant_name'),
        ),
        migrations.AddConstraint(
            model_name='diningtable',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'number'), name='uq_r_table__tenant_number'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'date'), name='uq_r_holiday__tenant_date'),
        ),
        migrations.AddConstraint(
            model_name='kitchenstation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'code'), name='uq_r_station__tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('tenant', 'code'), name='uq_r_printer__tenant_code'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='restaurantgstprofile',
                    name='restaurant',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_profile', to='restaurant.restaurant'),
                ),
                migrations.AddField(
                    model_name='restaurantgstprofile',
                    name='tenant',
                    field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant'),
                ),
                migrations.AddField(
                    model_name='restaurantsettings',
                    name='restaurant',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurant.restaurant'),
                ),
                migrations.AddField(
                    model_name='restaurantsettings',
                    name='tenant',
                    field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant'),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='BranchGSTProfile',
        ),
        migrations.DeleteModel(
            name='BranchSettings',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='restaurantgstprofile',
                    constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('restaurant',), name='uq_r_gst__restaurant'),
                ),
                migrations.AddConstraint(
                    model_name='restaurantsettings',
                    constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('restaurant',), name='uq_r_settings__restaurant'),
                ),
            ],
        ),
    ]
