# Generated by Django 5.2.15 on 2026-06-28 05:57

import django.db.models.deletion
import shared.infrastructure.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant_branch',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('churned', 'Churned')], db_index=True, default='trial', max_length=16)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
            ],
            options={
                'db_table': 'tenant',
                'indexes': [models.Index(condition=models.Q(('status', 'churned'), _negated=True), fields=['status'], name='ix_tenant__status_live')],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_currency__regex', '^[A-Z]{3}$')), name='ck_tenant__currency_format')],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='tenants.branch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_floor',
                'ordering': ['priority', 'name'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CashCounter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_counters', to='tenants.branch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_cash_counter',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='branch',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('invoice_footer', models.TextField(blank=True)),
                ('printer_settings', models.JSONField(blank=True, default=dict)),
                ('kitchen_settings', models.JSONField(blank=True, default=dict)),
                ('discount_rules', models.JSONField(blank=True, default=dict)),
                ('tax_rules', models.JSONField(blank=True, default=dict)),
                ('notification_settings', models.JSONField(blank=True, default=dict)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('language', models.CharField(default='en', max_length=10)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_configuration',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_domain',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='vacant', max_length=20)),
                ('qr_code_url', models.CharField(blank=True, max_length=500)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tenants.floor')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_table',
                'ordering': ['number'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('floor', 'number'), name='uq_table__floor_number')],
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenants.branch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_holiday',
                'ordering': ['date'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('branch', 'date'), name='uq_holiday__branch_date')],
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_branch__tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='tenantconfiguration',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_tenant_configuration__tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantdomain',
            index=models.Index(fields=['tenant'], name='ix_tenant_domain__tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenantdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tenant',), name='uq_tenant_domain__one_primary'),
        ),
    ]
