# Generated by Django 5.2.15 on 2026-06-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('hotel', 'Hotel'), ('cloud_kitchen', 'Cloud Kitchen')], default='restaurant', max_length=50),
        ),
    ]
