# Generated by Django 5.2.15 on 2026-06-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='table',
            name='uq_table__floor_number',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='table',
            name='floor',
        ),

        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tenants.branch'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('branch', 'number'), name='uq_table__branch_number'),
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
