# Generated by Django 5.2.15 on 2026-07-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_remove_floor_branch_remove_floor_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='holiday',
            name='uq_holiday__branch_date',
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='uq_table__branch_number',
        ),
        migrations.RemoveField(
            model_name='cashcounter',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='table',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='branch',
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('tenant', 'date'), name='uq_holiday__tenant_date'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uq_table__tenant_number'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
