# Generated by Django 5.2.15 on 2026-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If true, disables tenant access temporarily.')),
                ('global_tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('platform_name', models.CharField(default='Nextora POS', max_length=100)),
                ('support_email', models.EmailField(default='support@nextorapos.com', max_length=254)),
                ('terms_url', models.URLField(blank=True)),
                ('privacy_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
    ]
