# Generated by Django 5.2.15 on 2026-07-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_user_failed_login_attempts_user_is_email_verified_and_more'),
        ('tenants', '0004_remove_branch_tenant_remove_cashcounter_branch_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='uq_membership__user_tenant_role_location',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='location_id',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'tenant', 'role'), name='uq_membership__user_tenant_role'),
        ),
    ]
