# Generated by Django 5.2.15 on 2026-06-28 05:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['tenant', 'occurred_at'], name='ix_audit__tenant_time'), models.Index(fields=['tenant', 'entity_type', 'entity_id', 'occurred_at'], name='ix_audit__entity'), models.Index(fields=['tenant', 'actor_id', 'occurred_at'], name='ix_audit__actor')],
            },
        ),
    ]
