# Generated by Django 5.2.15 on 2026-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='printer',
            name='connection_type',
            field=models.CharField(choices=[('usb', 'USB'), ('lan', 'LAN'), ('wifi', 'Wi-Fi'), ('bluetooth', 'Bluetooth')], default='lan', max_length=20),
        ),
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printer',
            name='model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='printer',
            name='paper_width',
            field=models.CharField(choices=[('80mm', '80mm'), ('58mm', '58mm'), ('a4', 'A4')], default='80mm', max_length=10),
        ),
        migrations.AddField(
            model_name='printer',
            name='port',
            field=models.IntegerField(default=9100),
        ),
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.CharField(default='online', max_length=20),
        ),
    ]
