# Generated by Django 5.2.15 on 2026-07-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_printer_brand_printer_connection_type_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_modifiers', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modifier',
            name='quantity_consumed',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='modifier',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
