# Generated by Django 5.2.15 on 2026-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_modifier_inventory_item_modifier_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='color_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='modifier',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='modifier',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount (₹)'), ('percentage', 'Percentage of Base (%)'), ('free', 'Free / No Charge')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='display_style',
            field=models.CharField(choices=[('buttons', 'Buttons / Chips'), ('checkboxes', 'Checkboxes / Radio list'), ('dropdown', 'Dropdown Select')], default='buttons', max_length=20),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='expand_by_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='internal_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='print_on_invoice',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='print_on_kitchen_ticket',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='print_on_restaurant_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='selection_type',
            field=models.CharField(choices=[('single', 'Single Choice (Radio / 1 max)'), ('multiple', 'Multiple Choice (Checkboxes / Multi)')], default='multiple', max_length=20),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='max_select_override',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='min_select_override',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='required_override',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
