# Generated by Django 5.2.15 on 2026-07-08 18:23

import django.db.models.deletion
import shared.infrastructure.models.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_modifier_color_code_modifier_description_and_more'),
        ('tenants', '0003_remove_floor_branch_remove_floor_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboOffer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=160)),
                ('internal_code', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/combos/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('offer_type', models.CharField(choices=[('fixed_price', 'Fixed Price'), ('bundle', 'Bundle'), ('percentage', 'Percentage'), ('flat_discount', 'Flat Discount'), ('buy_x_get_y', 'Buy X Get Y')], default='fixed_price', max_length=30)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority offers apply first in auto-detection')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('available_days', models.JSONField(blank=True, default=list)),
                ('order_types', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'combo_offer',
                'ordering': ['sort_order', 'name'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComboGroup',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('min_selections', models.PositiveIntegerField(default=1)),
                ('max_selections', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='catalog.combooffer')),
            ],
            options={
                'db_table': 'combo_group',
                'ordering': ['sort_order'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComboGroupItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_by', models.UUIDField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('upgrade_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.combogroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'db_table': 'combo_group_item',
                'ordering': ['sort_order'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('group', 'product'), name='uq_combo_group_item')],
            },
            bases=(shared.infrastructure.models.base.AuditModelTrackerMixin, models.Model),
        ),
    ]
