# Generated by Django 5.2.15 on 2026-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_combooffer_combogroup_combogroupitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='combooffer',
            name='current_uses',
            field=models.PositiveIntegerField(default=0, help_text='Total overall redemptions'),
        ),
        migrations.AddField(
            model_name='combooffer',
            name='customer_eligibility',
            field=models.CharField(choices=[('all', 'All Customers'), ('new', 'New Customers Only'), ('returning', 'Returning Customers Only'), ('vip', 'VIP Customers'), ('loyalty', 'Loyalty Members')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='combooffer',
            name='min_cart_items',
            field=models.PositiveIntegerField(default=0, help_text='Minimum total items required in the cart'),
        ),
        migrations.AddField(
            model_name='combooffer',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart subtotal required to unlock this offer', max_digits=12),
        ),
        migrations.AddField(
            model_name='combooffer',
            name='usage_limit_type',
            field=models.CharField(choices=[('unlimited', 'Unlimited'), ('once_per_order', 'Once Per Order'), ('once_per_customer', 'Once Per Customer'), ('daily', 'Daily Limit'), ('monthly', 'Monthly Limit'), ('overall', 'Overall Usage Limit')], default='unlimited', max_length=20),
        ),
        migrations.AddField(
            model_name='combooffer',
            name='usage_limit_value',
            field=models.PositiveIntegerField(default=0, help_text='Limit value (e.g., 1 for once per order, 5 for daily limit)'),
        ),
    ]
