# Generated by Django 5.2.15 on 2026-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_combooffer_current_uses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenstation',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='location_id',
        ),
        migrations.AddField(
            model_name='combooffer',
            name='eligibility_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='combooffer',
            name='eligibility_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
