# Generated by Django 5.2.15 on 2026-07-14 18:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_default_plans'),
        ('tenants', '0004_remove_branch_tenant_remove_cashcounter_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTrialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Automatically grant a free trial on new restaurant registrations.')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Duration of the free trial in days (e.g. 7, 14, 30).')),
                ('grace_days', models.PositiveIntegerField(default=3, help_text='Grace period after trial expiration before blocking transaction operations.')),
                ('banner_message', models.CharField(default='Free Trial — {days} Days Remaining. Upgrade before your trial expires.', help_text='Banner template. Use {days} for dynamic countdown.', max_length=255)),
                ('expired_message', models.CharField(default='Your free trial has expired. Please choose a subscription plan to continue using Nextora POS.', help_text='Message shown when trial has expired and operations are locked.', max_length=255)),
                ('reminder_days_before', models.PositiveIntegerField(default=3, help_text='Days before expiration to trigger reminder notifications.')),
            ],
            options={
                'verbose_name': 'Global Trial Configuration',
                'verbose_name_plural': 'Global Trial Configuration',
                'db_table': 'global_trial_config',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionVisibilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_daily', models.BooleanField(default=False)),
                ('show_weekly', models.BooleanField(default=False)),
                ('show_monthly', models.BooleanField(default=True)),
                ('show_quarterly', models.BooleanField(default=False)),
                ('show_half_yearly', models.BooleanField(default=False)),
                ('show_yearly', models.BooleanField(default=True)),
                ('show_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Subscription Visibility Configuration',
                'verbose_name_plural': 'Subscription Visibility Configuration',
                'db_table': 'subscription_visibility_config',
            },
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly'), ('custom', 'Custom Duration')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='plan',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='plan',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='subscription',
            name='applied_coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly'), ('custom', 'Custom Duration')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly'), ('custom', 'Custom Duration')], max_length=16),
        ),
        migrations.CreateModel(
            name='SubscriptionCoupon',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total maximum redemptions across all users.', null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1, help_text='Maximum times a single tenant can apply this coupon.')),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, related_name='coupons', to='billing.plan')),
            ],
            options={
                'db_table': 'subscription_coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usages', to='billing.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='tenants.tenant')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='billing.subscriptioncoupon')),
            ],
            options={
                'db_table': 'coupon_usage',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionDiscount',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('scope', models.CharField(choices=[('platform', 'Entire Platform'), ('tenant', 'Specific Restaurant'), ('plan', 'Specific Plan')], default='platform', max_length=16)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='billing.plan')),
                ('target_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'subscription_discount',
            },
        ),
        migrations.CreateModel(
            name='TenantPriceOverride',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_free', models.BooleanField(default=False, help_text='If checked, tenant gets this plan for ₹0/Free.')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='billing.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_price_override',
                'unique_together': {('tenant', 'plan')},
            },
        ),
    ]
