# Generated by Django 5.2.15 on 2026-07-14 19:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_remove_limits_add_popular_gst_inclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncoupon',
            name='description',
            field=models.TextField(blank=True, help_text="Public description (e.g. '50% off for Grand Opening')"),
        ),
        migrations.AddField(
            model_name='subscriptioncoupon',
            name='eligibility',
            field=models.CharField(choices=[('all', 'All Customers'), ('new_only', 'New Customers Only'), ('existing', 'Existing Customers Only'), ('trial_users', 'Trial Users Only')], default='all', max_length=32),
        ),
        migrations.AddField(
            model_name='subscriptioncoupon',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private notes for Super Admin'),
        ),
        migrations.AddField(
            model_name='subscriptioncoupon',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptioncoupon',
            name='maximum_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cap for percentage discounts', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncoupon',
            name='minimum_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart value required', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioncoupon',
            name='name',
            field=models.CharField(default='Untitled Coupon', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='Short tagline shown on pricing cards'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='display_name',
            field=models.CharField(blank=True, help_text='Customer-facing name shown on pricing pages', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower = appears first on pricing page'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Exact number of days this plan is valid after activation'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly'), ('custom', 'Custom Duration')], default='monthly', help_text='Billing interval type (determines duration_days if not custom)', max_length=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='grace_days',
            field=models.PositiveIntegerField(default=7, help_text='Grace period after expiration before access is revoked'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='GST/tax percentage applied to this plan', max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive plans are hidden everywhere and not selectable'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected on the registration wizard'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Show 'Featured' badge"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text="Show 'Recommended' badge"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Internal plan name', max_length=100),
        ),
        migrations.AlterField(
            model_name='plan',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original/MRP price before discount', max_digits=14),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Effective selling price charged to the customer', max_digits=14),
        ),
    ]
