# Generated by Django 5.2.15 on 2026-07-23 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscriptioncoupon_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_pricing',
            field=models.BooleanField(default=False, help_text="If True, shows 'Custom Pricing' instead of a numeric amount"),
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_discount_percentage',
            field=models.PositiveIntegerField(default=16, help_text='Discount percentage for yearly billing on the frontend toggle'),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Up to 3 branches'", max_length=255)),
                ('is_included', models.BooleanField(default=True, help_text='If False, the feature will appear crossed out')),
                ('display_order', models.IntegerField(default=0, help_text='Lower = appears first on the list')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='billing.plan')),
            ],
            options={
                'db_table': 'plan_feature',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
